# -*- coding: utf-8 -*-
"""HackLYTICS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s_-J1TA91150_fzmQlffN7wKwgE__Bw7
"""

import pandas as pd
import numpy as np
import joblib
import json
from sklearn.ensemble import RandomForestRegressor
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.inspection import permutation_importance
import xgboost as xgb

from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

df = pd.read_csv('career_arcs.csv')
print(f"Loaded {len(df)} players from career_arcs.csv")
print(f"Players with Year 5 data: {df['y5_pts'].notna().sum()}")

# Basic deltas
df['delta_pts'] = df['y2_pts'] - df['y1_pts']
df['delta_ast'] = df['y2_ast'] - df['y1_ast']
df['delta_min'] = df['y2_min'] - df['y1_min']

# Basic derived
df['y2_ast_tov'] = df['y2_ast'] / (df['y2_tov'] + 0.1)
df['draft_pick'] = pd.to_numeric(df['draft_pick'], errors='coerce').fillna(60)

# 1. Skill Diversity Index
df['skill_diversity'] = (
    (df['delta_pts'] > 2).astype(int) +
    (df['delta_ast'] > 1).astype(int) +
    ((df['y2_fg3_pct'] - df['y1_fg3_pct']) > 0.03).astype(int)
)

# 2. Usage to Efficiency Ratio
df['usage_to_efficiency'] = df['y2_pts'] / (df['y2_fg_pct'] + 0.01)

# 3. Draft Overperformance
df['overperform_draft'] = df['y2_pts'] - (25 - df['draft_pick'] * 0.3)

# 4. Minutes Trajectory (percentage growth)
df['minutes_trajectory'] = df['delta_min'] / (df['y1_min'] + 1)

# 5. Free Throw Improvement
df['ft_pct_improvement'] = df['y2_ft_pct'] - df['y1_ft_pct']

print(f"   - skill_diversity: avg = {df['skill_diversity'].mean():.2f}")
print(f"   - usage_to_efficiency: avg = {df['usage_to_efficiency'].mean():.2f}")
print(f"   - overperform_draft: avg = {df['overperform_draft'].mean():.2f}")
print(f"   - minutes_trajectory: avg = {df['minutes_trajectory'].mean():.2f}")
print(f"   - ft_pct_improvement: avg = {df['ft_pct_improvement'].mean():.2f}")

import os

# Create folder structure
os.makedirs('models/path1', exist_ok=True)
os.makedirs('models/path2', exist_ok=True)
os.makedirs('data', exist_ok=True)

print("✅ Created folder structure:")
print("   - models/path1/")
print("   - models/path2/")
print("   - data/")

# Cluster on Year 2 stats only
cluster_features = ['y2_pts', 'y2_reb', 'y2_ast', 'y2_fg3_pct', 'y2_fg_pct', 'y2_min']

scaler = StandardScaler()
X_cluster = df[cluster_features].fillna(0)
X_cluster_scaled = scaler.fit_transform(X_cluster)

kmeans = KMeans(n_clusters=5, random_state=42, n_init=10)
df['cluster'] = kmeans.fit_predict(X_cluster_scaled)

print(f"Assigned {len(df)} players to 5 clusters")
print("\nCluster Distribution:")
print(df['cluster'].value_counts().sort_index())

# Calculate cluster stats
cluster_stats_list = []
for cluster_id in range(5):
    cluster_data = df[df['cluster'] == cluster_id]

    stats = {
        'cluster_id': cluster_id,
        'count': len(cluster_data),
        'y2_pts': cluster_data['y2_pts'].mean(),
        'y2_reb': cluster_data['y2_reb'].mean(),
        'y2_ast': cluster_data['y2_ast'].mean(),
        'y2_fg3_pct': cluster_data['y2_fg3_pct'].mean(),
        'delta_pts': cluster_data['delta_pts'].mean(),
    }
    cluster_stats_list.append(stats)

cluster_stats_df = pd.DataFrame(cluster_stats_list)

# Save (shared by both paths)
joblib.dump(scaler, 'models/scaler.pkl')
joblib.dump(kmeans, 'models/kmeans_model.pkl')
cluster_stats_df.to_csv('data/cluster_stats.csv', index=False)

print("\n Saved clustering artifacts")

from sklearn.model_selection import train_test_split

# Only use players with Year 5 data
df_with_y5 = df[df['y5_pts'].notna()].copy()

print(f"Total players with Year 5 data: {len(df_with_y5)}")
print(f"Draft year range: {df_with_y5['draft_year'].min():.0f} - {df_with_y5['draft_year'].max():.0f}")

# Random split with stratification
train_df, test_df = train_test_split(
    df_with_y5,
    test_size=0.2,
    random_state=42,
    stratify=df_with_y5['cluster']
)

print(f"\nTrain: {len(train_df)} players (80%)")
print(f"Test:  {len(test_df)} players (20%)")
print("\nCluster distribution:")
print("Train:", train_df['cluster'].value_counts().sort_index().tolist())
print("Test: ", test_df['cluster'].value_counts().sort_index().tolist())

TARGET = 'y5_pts'

# ==========================================
# PATH 1: BASELINE METHODOLOGY
# ==========================================

# Define PATH 1 features (basic only)
FEATURES_PATH1 = [
    # Year 2 stats
    'y2_pts', 'y2_reb', 'y2_ast', 'y2_min',
    'y2_fg_pct', 'y2_fg3_pct', 'y2_ft_pct',

    # Basic deltas
    'delta_pts', 'delta_ast', 'delta_min',

    # Derived
    'y2_ast_tov', 'draft_pick'
]

print(f"\n Path 1 Features: {len(FEATURES_PATH1)}")

X_train_p1 = train_df[FEATURES_PATH1].fillna(0)
y_train_p1 = train_df[TARGET]
X_test_p1 = test_df[FEATURES_PATH1].fillna(0)
y_test_p1 = test_df[TARGET]

# ==========================================
# PATH 1: TRAIN MODELS (NO TUNING)
# ==========================================

print("\n" + "="*50)
print("PATH 1: TRAINING MODELS")
print("="*50)

import time

# XGBoost with DEFAULT parameters
print("\n Training XGBoost (default params)...")
start_time = time.time()

model_xgb_p1 = xgb.XGBRegressor(
    n_estimators=200,
    learning_rate=0.05,
    max_depth=4,
    random_state=42,
    verbosity=0
)
model_xgb_p1.fit(X_train_p1, y_train_p1)

xgb_p1_time = time.time() - start_time

# Predictions
train_pred_xgb_p1 = model_xgb_p1.predict(X_train_p1)
test_pred_xgb_p1 = model_xgb_p1.predict(X_test_p1)

# Metrics
xgb_p1_train_mae = mean_absolute_error(y_train_p1, train_pred_xgb_p1)
xgb_p1_test_mae = mean_absolute_error(y_test_p1, test_pred_xgb_p1)
xgb_p1_test_r2 = r2_score(y_test_p1, test_pred_xgb_p1)

print(f"   Train MAE: {xgb_p1_train_mae:.2f} PPG")
print(f"   Test MAE:  {xgb_p1_test_mae:.2f} PPG")
print(f"   Test R²:   {xgb_p1_test_r2:.3f}")
print(f"   Time: {xgb_p1_time:.1f}s")

# Random Forest with DEFAULT parameters
print("\n Training Random Forest (default params)...")
start_time = time.time()

model_rf_p1 = RandomForestRegressor(
    n_estimators=200,
    max_depth=10,
    random_state=42,
    n_jobs=-1
)
model_rf_p1.fit(X_train_p1, y_train_p1)

rf_p1_time = time.time() - start_time

# Predictions
train_pred_rf_p1 = model_rf_p1.predict(X_train_p1)
test_pred_rf_p1 = model_rf_p1.predict(X_test_p1)

# Metrics
rf_p1_train_mae = mean_absolute_error(y_train_p1, train_pred_rf_p1)
rf_p1_test_mae = mean_absolute_error(y_test_p1, test_pred_rf_p1)
rf_p1_test_r2 = r2_score(y_test_p1, test_pred_rf_p1)

print(f"   Train MAE: {rf_p1_train_mae:.2f} PPG")
print(f"   Test MAE:  {rf_p1_test_mae:.2f} PPG")
print(f"   Test R²:   {rf_p1_test_r2:.3f}")
print(f"   Time: {rf_p1_time:.1f}s")

# Pick best for Path 1
if xgb_p1_test_mae < rf_p1_test_mae:
    best_model_p1 = model_xgb_p1
    best_model_p1_name = "XGBoost"
    best_p1_mae = xgb_p1_test_mae
    best_p1_r2 = xgb_p1_test_r2
    best_p1_train_mae = xgb_p1_train_mae
else:
    best_model_p1 = model_rf_p1
    best_model_p1_name = "Random Forest"
    best_p1_mae = rf_p1_test_mae
    best_p1_r2 = rf_p1_test_r2
    best_p1_train_mae = rf_p1_train_mae

print(f"\nPATH 1 Winner: {best_model_p1_name} (MAE: {best_p1_mae:.2f})")

# ==========================================
# PATH 1: ARCHETYPE MODELS
# ==========================================

archetype_models_p1 = {}
archetype_metrics_p1 = {}

for cluster_id in range(5):
    cluster_train = train_df[train_df['cluster'] == cluster_id]
    cluster_test = test_df[test_df['cluster'] == cluster_id]

    print(f"\nCluster {cluster_id}: ", end="")

    if len(cluster_train) < 20:
        print(f"SKIPPED (only {len(cluster_train)} samples)")
        archetype_metrics_p1[cluster_id] = {
            'status': 'insufficient_data',
            'train_size': len(cluster_train),
            'test_size': len(cluster_test)
        }
        continue

    print(f"Training on {len(cluster_train)} samples")

    X_cluster_train = cluster_train[FEATURES_PATH1].fillna(0)
    y_cluster_train = cluster_train[TARGET]

    # Use same model type as best general model
    if best_model_p1_name == "XGBoost":
        model = xgb.XGBRegressor(n_estimators=200, learning_rate=0.05, max_depth=4, random_state=42, verbosity=0)
    else:
        model = RandomForestRegressor(n_estimators=200, max_depth=10, random_state=42, n_jobs=-1)

    model.fit(X_cluster_train, y_cluster_train)

    if len(cluster_test) > 0:
        X_cluster_test = cluster_test[FEATURES_PATH1].fillna(0)
        y_cluster_test = cluster_test[TARGET]

        cluster_pred = model.predict(X_cluster_test)
        cluster_train_pred = model.predict(X_cluster_train)

        cluster_mae = mean_absolute_error(y_cluster_test, cluster_pred)
        cluster_train_mae = mean_absolute_error(y_cluster_train, cluster_train_pred)

        archetype_models_p1[cluster_id] = model
        archetype_metrics_p1[cluster_id] = {
            'status': 'trained',
            'train_size': len(cluster_train),
            'test_size': len(cluster_test),
            'train_mae': cluster_train_mae,
            'mae': cluster_mae
        }

        print(f"   Test MAE: {cluster_mae:.2f} PPG")
    else:
        archetype_metrics_p1[cluster_id] = {
            'status': 'no_test_data',
            'train_size': len(cluster_train),
            'test_size': 0
        }

# Calculate weighted average
total_samples_p1 = 0
total_error_p1 = 0

for cid, metrics in archetype_metrics_p1.items():
    if metrics.get('status') == 'trained':
        total_samples_p1 += metrics['test_size']
        total_error_p1 += metrics['mae'] * metrics['test_size']

archetype_avg_mae_p1 = total_error_p1 / total_samples_p1 if total_samples_p1 > 0 else None

print(f"\n Archetype Models Avg MAE: {archetype_avg_mae_p1:.2f}" if archetype_avg_mae_p1 else "\n No valid archetype models")

# Save models
joblib.dump(model_xgb_p1, 'models/path1/xgb_model.pkl')
joblib.dump(model_rf_p1, 'models/path1/rf_model.pkl')
joblib.dump(best_model_p1, 'models/path1/final_model.pkl')

for cid, model in archetype_models_p1.items():
    joblib.dump(model, f'models/path1/archetype_model_{cid}.pkl')

print(f" Saved {3 + len(archetype_models_p1)} models to models/path1/")

# Feature importance
from sklearn.inspection import permutation_importance

result_p1 = permutation_importance(
    best_model_p1, X_test_p1, y_test_p1,
    n_repeats=10, random_state=42, n_jobs=-1
)

importance_p1_df = pd.DataFrame({
    'feature': FEATURES_PATH1,
    'importance': result_p1.importances_mean,
    'std': result_p1.importances_std
}).sort_values('importance', ascending=False)

importance_p1_df.to_csv('data/feature_importance_path1.csv', index=False)

# Naive baseline
test_df['naive_prediction'] = test_df['y2_pts']
test_clean = test_df.dropna(subset=['y5_pts', 'y2_pts'])

naive_mae_p1 = mean_absolute_error(test_clean['y5_pts'], test_clean['naive_prediction'])
naive_r2_p1 = r2_score(test_clean['y5_pts'], test_clean['naive_prediction'])
improvement_p1 = ((naive_mae_p1 - best_p1_mae) / naive_mae_p1) * 100

# Metadata
metadata_p1 = {
    'path': 'Path 1 - Baseline',
    'best_model': best_model_p1_name,
    'num_features': len(FEATURES_PATH1),
    'hyperparameter_tuning': False,
    'train_mae': round(float(best_p1_train_mae), 2),
    'test_mae': round(float(best_p1_mae), 2),
    'test_r2': round(float(best_p1_r2), 3),
    'xgb_mae': round(float(xgb_p1_test_mae), 2),
    'rf_mae': round(float(rf_p1_test_mae), 2),
    'xgb_time': round(float(xgb_p1_time), 1),
    'rf_time': round(float(rf_p1_time), 1),
    'naive_mae': round(float(naive_mae_p1), 2),
    'improvement_pct': round(float(improvement_p1), 1),
    'train_size': len(train_df),
    'test_size': len(test_df)
}

with open('data/model_metadata_path1.json', 'w') as f:
    json.dump(metadata_p1, f, indent=2)

# Archetype analysis
archetype_comparison_p1 = {
    'general_mae': float(best_p1_mae),
    'archetype_mae': float(archetype_avg_mae_p1) if archetype_avg_mae_p1 else None,
    'cluster_metrics': {int(k): v for k, v in archetype_metrics_p1.items()}
}

with open('data/archetype_analysis_path1.json', 'w') as f:
    json.dump(archetype_comparison_p1, f, indent=2)

# Test predictions
test_predictions_p1 = test_df[['name', 'draft_year', 'y5_pts', 'y2_pts', 'cluster']].copy()
test_predictions_p1['predicted_y5_pts'] = best_model_p1.predict(X_test_p1)
test_predictions_p1['error'] = np.abs(test_predictions_p1['y5_pts'] - test_predictions_p1['predicted_y5_pts'])
test_predictions_p1 = test_predictions_p1.sort_values('error')
test_predictions_p1.to_csv('data/test_predictions_path1.csv', index=False)

# All predictions
df['predicted_y5_pts_path1'] = best_model_p1.predict(df[FEATURES_PATH1].fillna(0))

print("Saved all Path 1 data files")

print(f"\n{'='*50}")
print("PATH 1 COMPLETE")
print(f"{'='*50}")
print(f"Best Model: {best_model_p1_name}")
print(f"Test MAE: {best_p1_mae:.2f} PPG")
print(f"Improvement over naive: {improvement_p1:.1f}%")

# ==========================================
# PATH 2: ADVANCED METHODOLOGY
# ==========================================

# Define PATH 2 features (all features)
FEATURES_PATH2 = [
    # Year 2 stats
    'y2_pts', 'y2_reb', 'y2_ast', 'y2_min',
    'y2_fg_pct', 'y2_fg3_pct', 'y2_ft_pct',

    # Basic deltas
    'delta_pts', 'delta_ast', 'delta_min',

    # Derived
    'y2_ast_tov', 'draft_pick',

    # Advanced features
    'skill_diversity',
    'usage_to_efficiency',
    'overperform_draft',
    'minutes_trajectory',
    'ft_pct_improvement'
]

print(f"\n Path 2 Features: {len(FEATURES_PATH2)}")
print(f"   Advanced features: {len(FEATURES_PATH2) - len(FEATURES_PATH1)}")

X_train_p2 = train_df[FEATURES_PATH2].fillna(0)
y_train_p2 = train_df[TARGET]
X_test_p2 = test_df[FEATURES_PATH2].fillna(0)
y_test_p2 = test_df[TARGET]

# ==========================================
# PATH 2: HYPERPARAMETER TUNING
# ==========================================

from sklearn.model_selection import GridSearchCV
import time

# XGBoost tuning
print("\n Tuning XGBoost (729 combinations, ~8 min)...")
start_time = time.time()

xgb_param_grid = {
    'n_estimators': [50, 100, 150],
    'learning_rate': [0.05, 0.1, 0.15],
    'max_depth': [2, 3, 4],
    'min_child_weight': [1, 3, 5],
    'subsample': [0.8, 0.9, 1.0],
    'colsample_bytree': [0.8, 0.9, 1.0]
}

xgb_grid = GridSearchCV(
    xgb.XGBRegressor(random_state=42, verbosity=0),
    xgb_param_grid,
    cv=5,
    scoring='neg_mean_absolute_error',
    n_jobs=-1,
    verbose=0
)

xgb_grid.fit(X_train_p2, y_train_p2)
xgb_p2_time = time.time() - start_time

model_xgb_p2 = xgb_grid.best_estimator_
xgb_p2_params = xgb_grid.best_params_

train_pred_xgb_p2 = model_xgb_p2.predict(X_train_p2)
test_pred_xgb_p2 = model_xgb_p2.predict(X_test_p2)

xgb_p2_train_mae = mean_absolute_error(y_train_p2, train_pred_xgb_p2)
xgb_p2_test_mae = mean_absolute_error(y_test_p2, test_pred_xgb_p2)
xgb_p2_test_r2 = r2_score(y_test_p2, test_pred_xgb_p2)

print(f"   Best params: {xgb_p2_params}")
print(f"   Train MAE: {xgb_p2_train_mae:.2f} PPG")
print(f"   Test MAE:  {xgb_p2_test_mae:.2f} PPG")
print(f"   Test R²:   {xgb_p2_test_r2:.3f}")
print(f"   Time: {xgb_p2_time:.1f}s")

# Random Forest tuning
print("\n Tuning Random Forest")
start_time = time.time()

rf_param_grid = {
    'n_estimators': [50, 100, 150],
    'max_depth': [5, 8, 10, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [2, 4, 6]
}

rf_grid = GridSearchCV(
    RandomForestRegressor(random_state=42, n_jobs=-1),
    rf_param_grid,
    cv=5,
    scoring='neg_mean_absolute_error',
    n_jobs=-1,
    verbose=0
)

rf_grid.fit(X_train_p2, y_train_p2)
rf_p2_time = time.time() - start_time

model_rf_p2 = rf_grid.best_estimator_
rf_p2_params = rf_grid.best_params_

train_pred_rf_p2 = model_rf_p2.predict(X_train_p2)
test_pred_rf_p2 = model_rf_p2.predict(X_test_p2)

rf_p2_train_mae = mean_absolute_error(y_train_p2, train_pred_rf_p2)
rf_p2_test_mae = mean_absolute_error(y_test_p2, test_pred_rf_p2)
rf_p2_test_r2 = r2_score(y_test_p2, test_pred_rf_p2)

print(f"   Best params: {rf_p2_params}")
print(f"   Train MAE: {rf_p2_train_mae:.2f} PPG")
print(f"   Test MAE:  {rf_p2_test_mae:.2f} PPG")
print(f"   Test R²:   {rf_p2_test_r2:.3f}")
print(f"   Time: {rf_p2_time:.1f}s")

# Pick best for Path 2
if xgb_p2_test_mae < rf_p2_test_mae:
    best_model_p2 = model_xgb_p2
    best_model_p2_name = "XGBoost"
    best_p2_mae = xgb_p2_test_mae
    best_p2_r2 = xgb_p2_test_r2
    best_p2_train_mae = xgb_p2_train_mae
    best_p2_params = xgb_p2_params
else:
    best_model_p2 = model_rf_p2
    best_model_p2_name = "Random Forest"
    best_p2_mae = rf_p2_test_mae
    best_p2_r2 = rf_p2_test_r2
    best_p2_train_mae = rf_p2_train_mae
    best_p2_params = rf_p2_params

print(f"\nPATH 2 Winner: {best_model_p2_name} (MAE: {best_p2_mae:.2f})")

# ==========================================
# PATH 2: ARCHETYPE MODELS (WITH TUNING)
# ==========================================

print("\n" + "="*50)
print("PATH 2: TUNED ARCHETYPE-SPECIFIC MODELS")
print("="*50)

archetype_models_p2 = {}
archetype_metrics_p2 = {}

for cluster_id in range(5):
    cluster_train = train_df[train_df['cluster'] == cluster_id]
    cluster_test = test_df[test_df['cluster'] == cluster_id]

    print(f"\nCluster {cluster_id}: ", end="")

    if len(cluster_train) < 20:
        print(f"SKIPPED (only {len(cluster_train)} samples)")
        archetype_metrics_p2[cluster_id] = {
            'status': 'insufficient_data',
            'train_size': len(cluster_train),
            'test_size': len(cluster_test)
        }
        continue

    print(f"Training on {len(cluster_train)} samples")

    X_cluster_train = cluster_train[FEATURES_PATH2].fillna(0)
    y_cluster_train = cluster_train[TARGET]

    # Use TUNED parameters
    if best_model_p2_name == "XGBoost":
        model = xgb.XGBRegressor(**best_p2_params, random_state=42, verbosity=0)
    else:
        model = RandomForestRegressor(**best_p2_params, random_state=42, n_jobs=-1)

    model.fit(X_cluster_train, y_cluster_train)

    if len(cluster_test) > 0:
        X_cluster_test = cluster_test[FEATURES_PATH2].fillna(0)
        y_cluster_test = cluster_test[TARGET]

        cluster_pred = model.predict(X_cluster_test)
        cluster_train_pred = model.predict(X_cluster_train)

        cluster_mae = mean_absolute_error(y_cluster_test, cluster_pred)
        cluster_train_mae = mean_absolute_error(y_cluster_train, cluster_train_pred)

        archetype_models_p2[cluster_id] = model
        archetype_metrics_p2[cluster_id] = {
            'status': 'trained',
            'train_size': len(cluster_train),
            'test_size': len(cluster_test),
            'train_mae': cluster_train_mae,
            'mae': cluster_mae
        }

        print(f"   Test MAE: {cluster_mae:.2f} PPG (overfit: {cluster_mae/cluster_train_mae:.1f}x)")
    else:
        archetype_metrics_p2[cluster_id] = {
            'status': 'no_test_data',
            'train_size': len(cluster_train),
            'test_size': 0
        }

# Calculate weighted average
total_samples_p2 = 0
total_error_p2 = 0

for cid, metrics in archetype_metrics_p2.items():
    if metrics.get('status') == 'trained':
        total_samples_p2 += metrics['test_size']
        total_error_p2 += metrics['mae'] * metrics['test_size']

archetype_avg_mae_p2 = total_error_p2 / total_samples_p2 if total_samples_p2 > 0 else None

print(f"\nArchetype Models Avg MAE: {archetype_avg_mae_p2:.2f}" if archetype_avg_mae_p2 else "\n No valid archetype models")

# Save models
joblib.dump(model_xgb_p2, 'models/path2/xgb_model.pkl')
joblib.dump(model_rf_p2, 'models/path2/rf_model.pkl')
joblib.dump(best_model_p2, 'models/path2/final_model.pkl')

for cid, model in archetype_models_p2.items():
    joblib.dump(model, f'models/path2/archetype_model_{cid}.pkl')

print(f"Saved {3 + len(archetype_models_p2)} models to models/path2/")

# Feature importance
result_p2 = permutation_importance(
    best_model_p2, X_test_p2, y_test_p2,
    n_repeats=10, random_state=42, n_jobs=-1
)

importance_p2_df = pd.DataFrame({
    'feature': FEATURES_PATH2,
    'importance': result_p2.importances_mean,
    'std': result_p2.importances_std
}).sort_values('importance', ascending=False)

importance_p2_df.to_csv('data/feature_importance_path2.csv', index=False)

# Naive baseline (same as Path 1)
naive_mae_p2 = naive_mae_p1  # Same test set
improvement_p2 = ((naive_mae_p2 - best_p2_mae) / naive_mae_p2) * 100

# Metadata
metadata_p2 = {
    'path': 'Path 2 - Advanced',
    'best_model': best_model_p2_name,
    'num_features': len(FEATURES_PATH2),
    'hyperparameter_tuning': True,
    'train_mae': round(float(best_p2_train_mae), 2),
    'test_mae': round(float(best_p2_mae), 2),
    'test_r2': round(float(best_p2_r2), 3),
    'xgb_mae': round(float(xgb_p2_test_mae), 2),
    'rf_mae': round(float(rf_p2_test_mae), 2),
    'xgb_time': round(float(xgb_p2_time), 1),
    'rf_time': round(float(rf_p2_time), 1),
    'naive_mae': round(float(naive_mae_p2), 2),
    'improvement_pct': round(float(improvement_p2), 1),
    'best_params': {k: (int(v) if isinstance(v, (np.integer, np.int64)) else float(v) if isinstance(v, (np.floating, np.float64)) else v)
                    for k, v in best_p2_params.items()},
    'train_size': len(train_df),
    'test_size': len(test_df)
}

with open('data/model_metadata_path2.json', 'w') as f:
    json.dump(metadata_p2, f, indent=2)

# Archetype analysis
archetype_comparison_p2 = {
    'general_mae': float(best_p2_mae),
    'archetype_mae': float(archetype_avg_mae_p2) if archetype_avg_mae_p2 else None,
    'cluster_metrics': {int(k): v for k, v in archetype_metrics_p2.items()}
}

with open('data/archetype_analysis_path2.json', 'w') as f:
    json.dump(archetype_comparison_p2, f, indent=2)

# Test predictions
test_predictions_p2 = test_df[['name', 'draft_year', 'y5_pts', 'y2_pts', 'cluster']].copy()
test_predictions_p2['predicted_y5_pts'] = best_model_p2.predict(X_test_p2)
test_predictions_p2['error'] = np.abs(test_predictions_p2['y5_pts'] - test_predictions_p2['predicted_y5_pts'])
test_predictions_p2 = test_predictions_p2.sort_values('error')
test_predictions_p2.to_csv('data/test_predictions_path2.csv', index=False)

# All predictions
df['predicted_y5_pts_path2'] = best_model_p2.predict(df[FEATURES_PATH2].fillna(0))

# Save combined predictions
df.to_csv('data/final_player_predictions.csv', index=False)

print("Saved all Path 2 data files")

print(f"\n{'='*50}")
print("PATH 2 COMPLETE")
print(f"{'='*50}")
print(f"Best Model: {best_model_p2_name}")
print(f"Test MAE: {best_p2_mae:.2f} PPG")
print(f"Improvement over naive: {improvement_p2:.1f}%")

from google.colab import files
import shutil
import os

print("Creating ZIP archives...")

# Create zips
shutil.make_archive('data_archive', 'zip', 'data')
shutil.make_archive('models_archive', 'zip', 'models')

print("\nDownloading...")

# Download
files.download('data_archive.zip')
files.download('models_archive.zip')